### ISSUE TITLE
能不能更新个纯代码布局的，不同大小图片的Demo

### ISSUE THREAD

**Issue by lzc1022** [liangdahong/UITableView-BMTemplateLayoutCell#3]

**Comment by lzc1022** [comment]
也就是网络图片的,图片大小不固定

**Comment by lzc1022** [comment]
[Uploading UITableView-BMTemplateLayoutCell-master.zip…]()
![4cf33773-2db5-4943-b1cd-a54ee015d850](https://user-images.githubusercontent.com/9947322/37891885-7857e496-3108-11e8-9051-2f881c103785.png)

**Comment by liangdahong** [comment]
@lzc12313  有时间写一个哈，其实也是一样的，网络图片自适应高度需要服务器返回图片高度即可。

**Comment by lzc1022** [comment]
[UITableView-BMTemplateLayoutCell-图片高度不固定.zip](https://github.com/liangdahong/UITableView-BMTemplateLayoutCell/files/1854220/UITableView-BMTemplateLayoutCell-.zip)
这是我写的demo，您帮我看一下

**Comment by liangdahong** [comment]
@lzc12313

**Comment by liangdahong** [comment]
@lzc12313   供参考，一般在处理网络图片自适应时需提供图片尺寸，  然后在赋值 Cell 时修改图片的约束。
Demo 中我模拟了图片高度，在具体的业务中可以由图片的尺寸做相应处理。

[UITableView-BMTemplateLayoutCell-图片高度不固定.zip](https://github.com/liangdahong/UITableView-BMTemplateLayoutCell/files/1860421/UITableView-BMTemplateLayoutCell-.zip)

**Comment by liangdahong** [comment]
效果图如下：

![2](https://user-images.githubusercontent.com/12118567/38093728-678c9e20-339e-11e8-95d6-2e57886a769e.gif)
