### ISSUE TITLE
maxYView问题

### ISSUE THREAD

**Issue by gaoshuangone** [liangdahong/UITableView-BMTemplateLayoutCell#4]
大佬，maxYView demo能用代码写一下吗，再cell中最后一个view设置为cell.maxYView吗，如果需要加常量，写在那个地方比较好

**Comment by liangdahong** [comment]
![image](https://user-images.githubusercontent.com/12118567/82796643-6edea200-9ea8-11ea-87c2-4659f75f519f.png)
```
/// 如果你的 Cell 中用来确定 Cell 所需高度的 View 是唯一的,
/// 请把此值设置为 YES，可提升一定的性能。
@property (nonatomic, assign) IBInspectable BOOL bm_maxYViewFixed;
```

请问你说的是  bm_maxYViewFixed 属性吗 ？ @xiamoweinuan

**Comment by liangdahong** [comment]
@xiamoweinuan  
![image](https://user-images.githubusercontent.com/12118567/82796791-b2d1a700-9ea8-11ea-9fa2-d028f41dfa0c.png)

如果是 maxYView 的话 ，这是一个私有的，外面不可以使用。【可能需要把他放到 m 文件更好】

**Comment by liangdahong** [comment]
加常量的话，可以写在 
![image](https://user-images.githubusercontent.com/12118567/82797027-10fe8a00-9ea9-11ea-95da-f654d4f07e13.png)

但更建议给 cell 的 maxYView 添加 top 约束来处理。

可查看使用文档：https://github.com/liangdahong/UITableViewDynamicLayoutCacheHeight#%E5%9B%BE%E6%96%87%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E

**Comment by gaoshuangone** [comment]
多谢，以后就决定用你这个了，祝维护的越来越好，有新问题也会及时反馈。
