### ISSUE TITLE
cell展开折叠好像有问题

### ISSUE THREAD

**Issue by zhangxiongwen** [liangdahong/UITableView-BMTemplateLayoutCell#5]

**Comment by zhangxiongwen** [comment]
就是内容太多只显示2行，点击展开后刷新cell，调用[self.tableView reloadRowsAtIndexPaths:@[indexPath] withRowAnimation:UITableViewRowAnimationNone];直接崩溃，如果调用[self.tableView reloadData]，cell的高度没变

**Comment by liangdahong** [comment]
用的最新版本吗？
看看如何实现【展开】和【折叠】效果的？

**Comment by zhangxiongwen** [comment]
如果根据cel展开还是折叠设置不同的缓存key，cell的高度是没问题的，如果调用[self.tableView reloadRowsAtIndexPaths:@[indexPath] withRowAnimation:UITableViewRowAnimationNone];会崩溃

**Comment by liangdahong** [comment]
如果使用 key 做缓存的话，刷新的时候不会更新缓存，所以必须用不同的 key ，或者用 indexpath 做缓存。

**Comment by liangdahong** [comment]
崩溃的话使用最新版本看看

**Comment by zhangxiongwen** [comment]
好像用indexpath 做缓存就没问题了，谢谢大佬

**Comment by liangdahong** [comment]
崩溃的问题怎么样？

**Comment by liangdahong** [comment]
崩溃的问题可能知道了 等一下去看看 😭

**Comment by liangdahong** [comment]
@zhangxiongwen https://github.com/liangdahong/UITableViewDynamicLayoutCacheHeight/releases/tag/5.1.0 已处理崩溃的问题，谢谢反馈。

**Comment by zhangxiongwen** [comment]
谢谢大佬！
