### ISSUE TITLE
项目导入框架后，如果我用代理返回高度，不使用缓存高度，调用刷新单行会崩溃

### ISSUE THREAD

**Issue by zhangxiongwen** [liangdahong/UITableView-BMTemplateLayoutCell#6]
项目导入框架后，如果我用代理返回高度
-(CGFloat)tableView:(UITableView *)tableView heightForRowAtIndexPath:(NSIndexPath *)indexPath{
    return 64;
}

调用刷新
[self.tableView reloadRowsAtIndexPaths:@[indexPath] withRowAnimation:UITableViewRowAnimationNone]
会崩溃，如下图

![image](https://user-images.githubusercontent.com/21216840/86009492-df02b980-ba4c-11ea-8928-417d126aed84.png)

**Comment by liangdahong** [comment]
找到原因了，等一下去处理，感谢🙏。

**Comment by liangdahong** [comment]
@zhangxiongwen 已处理，可以使用最新代码尝试。或者使用https://github.com/liangdahong/UITableViewDynamicLayoutCacheHeight/releases/tag/5.1.1   。
