### ISSUE TITLE
不使用框架缓存，用代理直接返回高度，tableView插入行的时候崩溃

### ISSUE THREAD

**Issue by zhangxiongwen** [liangdahong/UITableView-BMTemplateLayoutCell#7]
插入数据的时候崩溃
[self.dataArray insertObject:dataModel atIndex:0];
            [self.tableView insertRowsAtIndexPaths:@[[NSIndexPath indexPathForRow:0 inSection:0]] withRowAnimation:UITableViewRowAnimationFade];

![image](https://user-images.githubusercontent.com/21216840/86128728-55b6ba00-bb14-11ea-9ec0-63cb85c68a55.png)

**Comment by zhangxiongwen** [comment]
- (void)tableView_dynamicLayout_insertRowsAtIndexPaths:(NSArray<NSIndexPath *> *)indexPaths withRowAnimation:(UITableViewRowAnimation)animation {
    if (self.isDynamicLayoutInitializationed) {
        // 清空缓存数据，这里可以优化，由于需要考虑太多的情况，暂时没有提供全面的测试方法，暂时直接全部刷新。
        [self _initCacheArrayWithDataSource:self.dataSource];
        kChangedCacheLog
    }
    [self tableView_dynamicLayout_insertRowsAtIndexPaths:indexPaths withRowAnimation:animation];
}
//崩溃在这里

**Comment by zhangxiongwen** [comment]
我错了，好像是我自己的数据问题

**Comment by liangdahong** [comment]
额额  看崩溃位置应该是数据源处理问题。
