### ISSUE TITLE
网络图片

### ISSUE THREAD

**Issue by lilin87788** [liangdahong/UITableView-BMTemplateLayoutCell#8]
如果图片是从网络下载的能自动适配高度吗？

**Comment by liangdahong** [comment]
网络图片的自适应需要使用者自己做，通常的接口设计
都是后台返图片尺寸，然后前端由后台给的尺寸做相关比例缩放和约束控制。

**Comment by lilin87788** [comment]
我公司的多个后台都说，21世纪了还需要后台返回图片尺寸，ios 太垃圾了，死活不改，为什么安卓不需要，就苹果名堂多，你能帮我说服我们公司的后台吗

**Comment by lilin87788** [comment]
我会急死克

**Comment by liangdahong** [comment]
😃 抓几个大厂的接口给他看看。

**Comment by liangdahong** [comment]
或者在图片下载完成的时候刷新 tableView。🏃

**Comment by lilin87788** [comment]
> 或者在图片下载完成的时候刷新 tableView。🏃

我现在就是这么做的，总觉得不完美。。。
