### ISSUE TITLE
麻烦提供下Cartfile 集成方式

### ISSUE THREAD

**Issue by AgoniNemo** [liangdahong/UITableView-BMTemplateLayoutCell#9]
麻烦提供下Cartfile 集成方式

**Comment by liangdahong** [comment]
好的，最近有时间弄一下。

**Comment by liangdahong** [comment]
@AgoniNemo 
- https://github.com/liangdahong/UITableViewDynamicLayoutCacheHeight/releases/tag/5.2.0 已支持 Carthage
